name: network
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none
environment:
  sdk: '>=2.15.1 <3.0.0'

dependencies:
  dio: ^5.4.1
  logger: ^2.1.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.25.2
